// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservAR.Infraestructure.Persistance;

#nullable disable

namespace ReservAR.Infraestructure.Migrations
{
    [DbContext(typeof(ReservarDbContext))]
    [Migration("20260207223446_update-relations")]
    partial class updaterelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservAR.Domain.AtributoAggregate.Atributo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Atributos", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.CanchaAggregate.AtributoCancha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdAtributo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCancha")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdAtributo");

                    b.HasIndex("IdCancha");

                    b.ToTable("AtributoCanchas", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.CanchaAggregate.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdComplejo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDeporte")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipoPiso")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double?>("Seña")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdComplejo");

                    b.HasIndex("IdDeporte");

                    b.HasIndex("IdTipoPiso");

                    b.ToTable("Canchas", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.ComplejoAggregate.Complejo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdDireccion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Online")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdDireccion")
                        .IsUnique()
                        .HasFilter("[IdDireccion] IS NOT NULL");

                    b.ToTable("Complejos", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.ComplejoAggregate.ServicioComplejo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdComplejo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdServicio")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdComplejo");

                    b.HasIndex("IdServicio");

                    b.ToTable("ServiciosComplejo", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.ConsumoAggregate.Consumo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdComplejo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdReserva")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdComplejo");

                    b.HasIndex("IdReserva");

                    b.ToTable("Consumos", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.DeporteAggregate.Deporte", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Deportes", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.DireccionAggregate.Direccion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoordenadaX")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CoordenadaY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Direcciones", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.DisponibilidadHorariaAggregate.DisponibilidadHoraria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoraDesde")
                        .HasColumnType("int");

                    b.Property<int>("HoraHasta")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdComplejo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdComplejo");

                    b.ToTable("DisponibilidadesHorarias", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.PisoAggregate.Piso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pisos", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.PrecioAggregate.Precio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCancha")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TipoPrecio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopeHorario")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCancha");

                    b.ToTable("Precios", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.ProductoAggregate.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdComplejo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("PrecioCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdComplejo");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.ProductoConsumoAggregate.ProductoConsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdConsumo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdConsumo");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductosConsumo", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.ReservaAggregate.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<bool>("Fijo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Hora")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCancha")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Pago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdCancha");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.RolAggregate.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.ServicioAggregate.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("ReservAR.Domain.UserAggregate.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdComplejo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRol")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdComplejo");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ReservAR.Infraestructure.Persistance.OutboxMessages.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("ReservAR.Domain.CanchaAggregate.AtributoCancha", b =>
                {
                    b.HasOne("ReservAR.Domain.AtributoAggregate.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("IdAtributo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.CanchaAggregate.Cancha", "Cancha")
                        .WithMany("Atributos")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("ReservAR.Domain.CanchaAggregate.Cancha", b =>
                {
                    b.HasOne("ReservAR.Domain.ComplejoAggregate.Complejo", "Complejo")
                        .WithMany("Canchas")
                        .HasForeignKey("IdComplejo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.DeporteAggregate.Deporte", "Deporte")
                        .WithMany("Canchas")
                        .HasForeignKey("IdDeporte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.PisoAggregate.Piso", "TipoPiso")
                        .WithMany("Canchas")
                        .HasForeignKey("IdTipoPiso")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Complejo");

                    b.Navigation("Deporte");

                    b.Navigation("TipoPiso");
                });

            modelBuilder.Entity("ReservAR.Domain.ComplejoAggregate.Complejo", b =>
                {
                    b.HasOne("ReservAR.Domain.DireccionAggregate.Direccion", "Direccion")
                        .WithOne()
                        .HasForeignKey("ReservAR.Domain.ComplejoAggregate.Complejo", "IdDireccion")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("ReservAR.Domain.ComplejoAggregate.ServicioComplejo", b =>
                {
                    b.HasOne("ReservAR.Domain.ComplejoAggregate.Complejo", "Complejo")
                        .WithMany("Servicios")
                        .HasForeignKey("IdComplejo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.ServicioAggregate.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complejo");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ReservAR.Domain.ConsumoAggregate.Consumo", b =>
                {
                    b.HasOne("ReservAR.Domain.ComplejoAggregate.Complejo", "Complejo")
                        .WithMany("Consumos")
                        .HasForeignKey("IdComplejo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.ReservaAggregate.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Complejo");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ReservAR.Domain.DisponibilidadHorariaAggregate.DisponibilidadHoraria", b =>
                {
                    b.HasOne("ReservAR.Domain.ComplejoAggregate.Complejo", "Complejo")
                        .WithMany("DisponibilidadesHorarias")
                        .HasForeignKey("IdComplejo")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservAR.Domain.PrecioAggregate.Precio", b =>
                {
                    b.HasOne("ReservAR.Domain.CanchaAggregate.Cancha", "Cancha")
                        .WithMany("Precios")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("ReservAR.Domain.ProductoAggregate.Producto", b =>
                {
                    b.HasOne("ReservAR.Domain.ComplejoAggregate.Complejo", "Complejo")
                        .WithMany("Productos")
                        .HasForeignKey("IdComplejo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Complejo");
                });

            modelBuilder.Entity("ReservAR.Domain.ProductoConsumoAggregate.ProductoConsumo", b =>
                {
                    b.HasOne("ReservAR.Domain.ConsumoAggregate.Consumo", "Consumo")
                        .WithMany("ProductosConsumo")
                        .HasForeignKey("IdConsumo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.ProductoAggregate.Producto", "Producto")
                        .WithMany("ProductosConsumo")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Consumo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ReservAR.Domain.ReservaAggregate.Reserva", b =>
                {
                    b.HasOne("ReservAR.Domain.CanchaAggregate.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.UserAggregate.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReservAR.Domain.UserAggregate.Usuario", b =>
                {
                    b.HasOne("ReservAR.Domain.ComplejoAggregate.Complejo", "Complejo")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdComplejo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReservAR.Domain.RolAggregate.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Complejo");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ReservAR.Domain.CanchaAggregate.Cancha", b =>
                {
                    b.Navigation("Atributos");

                    b.Navigation("Precios");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservAR.Domain.ComplejoAggregate.Complejo", b =>
                {
                    b.Navigation("Canchas");

                    b.Navigation("Consumos");

                    b.Navigation("DisponibilidadesHorarias");

                    b.Navigation("Productos");

                    b.Navigation("Servicios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ReservAR.Domain.ConsumoAggregate.Consumo", b =>
                {
                    b.Navigation("ProductosConsumo");
                });

            modelBuilder.Entity("ReservAR.Domain.DeporteAggregate.Deporte", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("ReservAR.Domain.PisoAggregate.Piso", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("ReservAR.Domain.ProductoAggregate.Producto", b =>
                {
                    b.Navigation("ProductosConsumo");
                });

            modelBuilder.Entity("ReservAR.Domain.UserAggregate.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
